---
##@ref https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#variables-and-vaults
ansible_ssh_user: "ubuntu"
current_user: "ubuntu"
server_name: "example.com"

#repo_git_url: "app_github_url"
#ansible_ssh_private_key_file: "/home/ubuntu/.ssh/"
php_version: 7.4
mcrypt_version: 1.0.3
app_work_dir: /var/www
#mysql config
#The Debian OS has a problem with creating a user:
# unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (2012, 'Error in server handshake')
mysql_host: "localhost"
mysql_db: db_bitrix
mysql_user: db_user
mysql_pass: db_user



#other config
sendmail: "info@example.com"
sendmail_full_name: "Site name"
#cache_driver: file
#session_driver: file
#app_env: production
#app_debug: false
#app_key: "your_app_key"
#app_name: "app_name"
#app_url: "your_app_url"
