---
- name: Remove Apache
  become: true
  apt:
    name: apache2
    state: absent
    #workaround Todo fix it
#- name: Remove useless dir
#  become: true
#  file:
#    state: absent
#    path: "/var/www/html/"
#  tags:
#    - nginx
#  notify: Restart Nginx

###

- name: Install Nginx web server
  become: true
  apt: 
    name: nginx 
    state: latest
  notify: Restart Nginx
  tags:
    - nginx


###
- name: Update nginx config files
  become: true
  template:
    src: templates/nginx.conf
    dest: "/etc/nginx/sites-available/default"
  tags:
    - nginx
  notify: Restart Nginx

###
- name: link nginx config
  become: true
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link
  tags:
    - nginx
  notify: Restart Nginx

- name: Update snapd 
  become: true
  command: snap install core 

- name: install certbot 
  become: true
  command: snap install --classic certbot
#have a bug todo
- name: prepare command 
  become: true
  shell: ln -s /snap/bin/certbot usr/bin/certbot

#uncomment only for real fqdn 
#- name: create certificate 
#  become: true
#  shell: certbot --nginx -d '{{ server_name }}' -d www.' {{ server_name }}' -n -m torgashev@yandex.ru  --agree-tos
#  tags:
#    - nginx
#  notify: Restart Nginx