---
- hosts: bitrix
#common options between modules
  #remote_user: root
  gather_facts: yes

  vars_files:
    - ./group_vars/vars.yml
  roles:
    - nginx
    - php
    - percona
    - memcached
    - postfix
    - git
  handlers:
    - include: handlers/main.yml
#
#just for sake of !!
#- name: Set date.timezone for FPM
#  lineinfile:
#    dest: /etc/php/{{php_version}}/fpm/php.ini
#    regexp: "date.timezone ="
#    line: "date.timezone = UTC"
#  tags:
#    - config-files
#  notify: Restart Nginx
